---
title: Spinning Flower Wheel
hero_image: images/banner.png
description: Get started with motors by creating a digital garden of spinning flowers or pinwheels
original_url: https://raspberrypi.org/learning/spinning-flower-wheel
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-1, community-0
interests: art
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Attach the Explorer HAT to your Raspberry Pi
- title: Prepare your motor and wheel
- title: Decorate your wheel with a flower or pinwheel
- title: Write code to make the motor turn
- title: Using a button to start your spinning program
- title: What next?
