---
title: Fleur Tournante
hero_image: images/banner.png
description: Commencer avec des moteurs en créant un jardin numérique de fleurs tournantes
  ou de moulins à vent
original_url: https://raspberrypi.org/learning/spinning-flower-wheel
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-1, community-0
interests: art
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Ce dont tu auras besoin
  completion: engaged
- title: Attacher l'Explorer HAT à ton Raspberry Pi
- title: Préparer ton moteur et ta roue
- title: Décorer ta roue avec une fleur ou un moulin à vent
- title: Écrire le code pour faire tourner le moteur
  completion: internal
- title: Utiliser un bouton pour démarrer ton programme de rotation
- title: Et ensuite ?
